### ISSUE TITLE
Glitches with Nexus Dock

### ISSUE THREAD

**Issue by RobinD42** [kangyu-california/PersistentWindows#123]
I use Nexus Dock (http://www.winstep.net/nexus.asp) and sometimes it will jump around the screen a little when PersistentWindows is active. Since the dock is not moveable with the mouse I can't do the Ctrl-Shift-Move mentioned in the Help doc. So it would be nice to have another way to specify windows that are to be ignored by PersistentWindows. Perhaps a command-line option to specify the process name? Or maybe a menu option that goes into a window selection mode where the next click will identify the window to be ignored?

**Comment by kangyu-california** [comment]
The main window of Nexus Dock is highly customized and is invisible to PW.
So it is unlikely the jump around (of main window) is caused by PW, I would think it is caused by Windows OS or even the app itself.

PW does see Nexus preference dialog (as it is a regular window) and can restore that one, and you may apply Ctrl-Shift-Move on that dialog as well.

FYI: The Nexus main window can be moved after select "undock" in "Screen Position" menu. Note that Ctrl-Shift-Move trick wont work on the main window as PW does not "see" the main window as restorable candidate for the beginning.

**Comment by RobinD42** [comment]
Okay, thanks for looking into it.

**Comment by kangyu-california** [comment]
new command option -ignore_process is added in release 5.26
