### ISSUE TITLE
VirtuaWin (v4.4+) compatibility

### ISSUE THREAD

**Issue by vhelin** [kangyu-california/PersistentWindows#128]
I'm a long time user of VirtuaWin, a virtual desktop manager (https://virtuawin.sourceforge.io/). I'd like to use PersistentWindows, but it doesn't seem to save the state of the windows on other than the current virtual screen. Would it be possible to add support for such a virtual desktop manager?

**Comment by kangyu-california** [comment]
PW relies on traditional Win32 APIs such as MoveWindow() which however may fail if the window belongs to another virtual desktop.
My opinion is Microsoft should address the API misbehave/incompatibility issue, so that applications like PW do not need to be aware of virtual desktop at all.

You may workaround the issue by capture each virtual desktop as a unique snapshot in PW, for example capture virtual desktop 1 to snapshot '1' etc. When switching back to virtual desktop 1, just invoke restore snapshot '1' in PW

Personally I would forgo virtual desktop and capture a snapshot for each unique window layout and just use command shortcut to switch between these snapshots (checkout PW online help page).

**Comment by kangyu-california** [comment]
It seems VirtualWin's implementation of virtual desktop does not comply with Microsoft's native one.
Closing the issue as not supported due to future compatibility concern.
