### ISSUE TITLE
Duplicate System Tray icons upon exiting the application and changing its location

### ISSUE THREAD

**Issue by crazy734** [kangyu-california/PersistentWindows#136]
Hello,

Thank you for this wonderful tool. However, when I tried exiting the tool, and changing the location of the .exe file to another location on my computer, editing the location of the script in the task scheduler, and finally running the .exe file from the new location once again, I saw that there are two duplicate icons of the PersistentWindows in the taskbar settings to display the icons in the system tray. Could you please help me to remove this bug?

Also, could you please let me know how to completely remove PersistentWindows from my System, the task bar settings and the System tray? I do not see it as an installed program anywhere in the programs and features of the control panel and even if I delete the source folder where PersistentWindows.exe file is located, it still shows in the taskbar settings to display which icons appear in the system tray.

**Comment by kangyu-california** [comment]
The duplicated icons (for each PW version) in taskbar setting is a Windows bug, I believe it is resolved in latest Windows 10 21H1 release.

PW creates C:\Users\<user_id>\AppData\Local\PersistentWindows dir in order to save windows to disk, that is all PW requires.
Windows OS might cache application history somewhere, which is out of control of PW.

**Comment by crazy734** [comment]
Okay thank you
