### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by HydroTRI** [kangyu-california/PersistentWindows#143]
I have been using this program for a while and I love it but recently, after sleeping my PC a few times when I start to use it again Persistent windows task is using 70-90% of my CPU until I close the program and reopen it. Then everything returns to normal. Any idea why this is happening?

**Comment by kangyu-california** [comment]
I suspect this is a known issue documented in readme, which boils down to a Win32 API failure that some window may become unresponsive when PW calls Win32 MoveWindow() to restore its position, as a result the main thread of PW stalls, which might explain the high cpu usage. 

The root cause of this issue is still unknown. I have experienced PW stall several times, mostly when recovering Visual Studio Code window which has a pending upgrade exclamation mark. The last time I had this issue is because of unresponsive google chrome windows. In both cases, PW will come back alive by upgrading VScode or kill the unresponsive chrome process.

Version 5.33 has a speculative fix for this issue, although It is not verified.

**Comment by HydroTRI** [comment]
Okay thanks for the response.
