### ISSUE TITLE
All browser windows keeps moving to the same location

### ISSUE THREAD

**Issue by GeeZuZz** [kangyu-california/PersistentWindows#178]
I recently upgraded to the latest version (from 5.35 i think).

After the update, my browser windows keeps getting moved to the same location.
I use the Vivaldi web browser, with 3 windows (one on each monitor). But they all keep being moved to the same location.

1. I put one window on each monitor, 
2. Press WIN+CTRL-RIGHT(arrow) to got to next desktop
3. Press WIN+CTRL-LEFT to go back
4. The 2 side monitor browser windows are now moved onto the center monitor window, so they are all on top of each other.

In the previous version this didn't happen.

Edit: Can confirm it does not happen in 5.35.

**Comment by kangyu-california** [comment]
Switching virtual desktops should not trigger the restore action of PW because the display config remains the same.
And I could not reproduce the issue on my setup.

To help me debug the issue, could you please post the PW event log at moment of wrong window movement?
Here is one example
![image](https://user-images.githubusercontent.com/59128756/190280503-a96ce57f-a6f0-4aad-9748-221bbb4f9207.png)

**Comment by GeeZuZz** [comment]
Strange, when I upgraded again, it does not do it anymore.

I was sure it was related to this app, because I was testing and confirming the issue multiple times, then I closed the app, downgraded it, and started it again, and it no longer happened.

But since it no longer happens now even when upgraded, I have no idea what caused it.
