### ISSUE TITLE
Windows 11 Notifications widget section goes to the left

### ISSUE THREAD

**Issue by kimpurcell** [kangyu-california/PersistentWindows#179]
Click on the date/time to bring up notifications.
It goes somewhere to the left of the screen with its right side cut off.

**Comment by kangyu-california** [comment]
Could not reproduce the issue on Windows 11.

Please upgrade to latest 5.38 release and reboot machine.

If the issue is still reproducible, please post event logs (around the time when the notification window get moved), as shown in following example
https://user-images.githubusercontent.com/59128756/190280503-a96ce57f-a6f0-4aad-9748-221bbb4f9207.png
