### ISSUE TITLE
Can't see or edit scheduled task

### ISSUE THREAD

**Issue by BrendanSimon** [kangyu-california/PersistentWindows#182]
I cannot see or edit the scheduled task I have created (or think I created).
My PW app does not seem to startup after a reboot (I have the `-delay_start 10` optional argument).

I have just upgraded to PW 5.39 and thought I better create a new scheduled task, but when I do I a get an error saying that folder already exists (i.e. I'm using the same task name, but I can't see/edit that task).

I'm not familiar with Windows scheduled tasks, so it's likely something I am doing wrong.

Thanks for any help.  Maybe it's a bug?

**Comment by kangyu-california** [comment]
On my PC the PW task is placed at the root directory.
![image](https://user-images.githubusercontent.com/59128756/192401395-13b6926f-7e69-47a7-9958-00227e6f6bfb.png)

You may have created PW task under one of the sub-folders in task scheduler library, 
Try to reuse existing task instead of creating a new one.

Instead of using task scheduler, you may also create a shortcut in windows startup folder
[link](https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd)
