### ISSUE TITLE
Window sneaking left after restore

### ISSUE THREAD

**Issue by OGNetheri** [kangyu-california/PersistentWindows#188]
It's a small issue but I have Discord window on 2nd monitor  top right. After every window restore (automatic) this one window crawls left a pixel or two. If i run restore from disk manually, it goes to where it should (and I've taken screnshot to disk multiple times after it's where it should be and still it just crawls left every time after monitor(s) are sleeping and they're enabled again). It's a minor issue as said and I was wondering is there some -option I could use for the specific window to maintain it's place or is there some glitch on the program itself as all the other windows's stay where they should?

**Comment by kangyu-california** [comment]
This reminds me of a [known_issue](https://github.com/kangyu-california/PersistentWindows/issues/56) dated back on Nov 10 2020, search "pixel" for more details in the discussion.

The thing is PersistentWindows calls Microsoft MoveWindow() API to restore window position.
However this API may fail to accurately restore window position if the window was snapped to screen corner.
A fix was made in PW version 5.5, and I have not heard similar issue since then.

I tried to snap Discord window to top left corner of second monitor, and PW auto restore seems to do fine.
Maybe the pixel level inaccuracy is hard to see for my short period of testing.

**Comment by OGNetheri** [comment]
I have snapping off, however I put the window with "free hand" to the exact match with the visible screen. This is somewhat weird issue, as the HWInfo window stays on it's place on the same 2nd monitor on the top left alignment.
