### ISSUE TITLE
Edge browser is offset from display when PC resumes from sleep and Edge is maximised to full screen

### ISSUE THREAD

**Issue by BladderFox** [kangyu-california/PersistentWindows#201]
Using Persistent Windows 5.40.
When I have Edge at full screen on my second display (connected via HDMI, primary display is connected via DisplayPort) and the PC resumes from sleep Edge is offset upward and to the left from the edges of the screen.
There is a thick black border at the bottom and to the right of the display. The mouse cannot enter this area.
The top and left hand side of the Edge window are off the display and cannot be accessed.
The mouse is not able to go off the top or left of the screen.

The only way I have found to resolve this is to close the Edge window from the taskbar and reopen Edge. This always fixes the error but it is a massive pain to have to do every few minutes. I never saw this issue before upgrading to 5.4. I had been using 5.39 for several months with no problems.
There has not been any recent change to the PC hardware configuration but I think there was an update to Edge and/or Windows recently.

**Comment by BladderFox** [comment]
Downgrading to 5.39 seems to fix the issue.

**Comment by kangyu-california** [comment]
I have tried Edge browser window in Maximized mode as well as in true full screen mode (such as playing youtube video in borderless style), and still can not reproduce the issue.

I need more details on the procedure to reproduce the issue, and what other apps are you running etc. A video clip would be very helpful.

BTW, PW restores 
all windows using the same procedure, so if the issue is specific to Edge browser, please bring the issue to Microsoft as well.

**Comment by kangyu-california** [comment]
there is no need to close and relaunch Edge browser,
You may want to try either of the following functions available in PW context menu or using mouse-keyboard command shortcut (checkout more details from Help menu)
1. restore from disk
2. restore from snapshot

**Comment by kangyu-california** [comment]
Could not reproduce the issue on 5.40, a detailed procedure to reproduce the issue is very important to me (a video clip is even better)

You may try either one of the following command line options as a fix.
-delay_auto_restore 3
-ignore_process "msedge.exe"

Refer to [help page](https://github.com/kangyu-california/PersistentWindows/blob/master/Help.md)  for details.

You may also workaround the issue by select "Restore windows from disk" in PW menu, there is no need to exit and relaunch Edge browser.

**Comment by kangyu-california** [comment]
close as not reproducible

**Comment by lxsli** [comment]
#203 has reoccurred with the delay_auto_restore setting in place

**Comment by lxsli** [comment]
it does work in the majority of cases though, I've only seen it fail once since applying that setting
