### ISSUE TITLE
Main taskbar is not restored to secondary monitor

### ISSUE THREAD

**Issue by KNP54** [kangyu-california/PersistentWindows#208]
I have the main taskbar positioned (with system tray and search) positioned on the bottom of the 2nd display.
My new monitor (displayport) takes 4 seconds to turn on and resuming from displays off makes all windows and task bar to move on my main monitor which turns on a lot faster than my second monitor. Hence why I tried PersistentWindows. The program works fine on my window positions but not the taskbar (it stays on my main display) when PersistentWindows does its magic.

OS: Windows 10 pro Version 22H2 build 19045.2604

**Comment by kangyu-california** [comment]
You may run PW with following command option to delay restore by 5 seconds, so that restore will start after the second monitor fully wakes up.
-delay_auto_restore 5

If that does not work, you may try 
[latest patch](https://github.com/kangyu-california/PersistentWindows/files/10775353/PersistentWindows5.40p1.zip)

**Comment by KNP54** [comment]
Sorry it doesn't work. Tried the latest patch you provided, the -delay_auto_restore 5 option, closing LittleBigMouse (https://github.com/mgth/LittleBigMouse), set all monitor scaling to 100% and unlocking the taskbar. Please note that main monitor is an ultrawide 3440x1440 125% scaling, and secondary monitor is a 4K 3840x2160 175% scaling and is positioned to the left of the main monitor.

**Comment by kangyu-california** [comment]
Taskbar restore across monitor is a hard problem, I can not fix it.
