### ISSUE TITLE
Google Chrome won't keep the original window size and position after restore

### ISSUE THREAD

**Issue by iminet** [kangyu-california/PersistentWindows#212]
When a Chrome window is not in full screen, after restore, that Chrome looses its previous window size and position.
This issue is about only Google Chrome and when the Chrome isn a smaller resizeable state. For example, Outlook 365 won't produce the issue at the same situation

Can you pls fix it?
Thanks.

**Comment by kangyu-california** [comment]
The issue is hard to reproduce.

I would like to try following steps
1. test manual restore (from snapshot or hard drive), if that works it means the fundamental algorithm of restore is not the culprit.
2. try -delay_auto_restore 5 command option, this helps to revert adversarial moves by OS or other competing applications.
3. make sure you did not press CTRL SHIFT keys while moving the chrome window, which accidentally put the chrome window into no-restore list.
