### ISSUE TITLE
Maximized window stays on top after turning the secondary display off

### ISSUE THREAD

**Issue by me21** [kangyu-california/PersistentWindows#225]
I have a laptop with secondary display connected over HDMI. There is maximized Firefox window on the second display. If it's active when I pull out HDMI cable, it is moved to the laptop's display while staying on top, covering the windows which were open on the laptop's display.

I tried to minimize Firefox window when HDMI is disconnected, but it didn't help: when I connect HDMI, the Firefox window is restored to the secondary display and maximized and made active. On the subsequent HDMI disconnection, Firefox window is moved to the laptop's display again, not minimized.

**Comment by kangyu-california** [comment]
> when I pull out HDMI cable, it is moved to the laptop's display while staying on top, covering the windows which were open on the laptop's display

This is done by windows OS or by the Firefox app itself, because PW does not know where the new position should be when pulling out HDMI cable for the very first time (i.e. PW does not move windows for a brand new display configuration).

Also I want to clarify the meaning of "staying on top", is the Firefox window become sticky as topmost, or you are able to bring covered window back to top?
By no means PW would turn on the topmost sticky flag of a window.

> On the subsequent HDMI disconnection, Firefox window is moved to the laptop's display again, not minimized

This is strange, did you give PW enough time to remember the minimized status (like 5 seconds) before pulling out HDMI cable again?
