### ISSUE TITLE
Not 'Saving to Disk'. (Worked for a long time. Only recently having problems - new update?)

### ISSUE THREAD

**Issue by Joeys3ph** [kangyu-california/PersistentWindows#234]
Often when my monitors/PC go to sleep or I have to restart my PC, 'Restore windows from Disk' will be greyed out upon trying to restore my windows.

This has never happened before until maybe a few weeks ago. Not totally sure if this started happening after updating to 5.41, but it has never happened before.

**Comment by kangyu-california** [comment]
The "Restore from Disk" menu is grey because the current display configuration is new to PW, this can happen whenever user changed scale factor or even slightly shift the relative offset between multiple monitors.

PW is unable to "reuse" the old capture from different display configuration.

Simply do a capture to disk operation to let PW permanently remember the current display config.

**Comment by Joeys3ph** [comment]
Hi! Sorry to open this problem again. I've looked around and can't find any results.

'Restore from Disk' isn't always greyed out. It has worked in the past. I recently updated to 5.42 and I'm still facing the same problem. 

'Restore from Disk' was working for a few days as usual. Today, my power went out. Upon restarting, 'Restore from Disk' is greyed out again and I had to reconfigure my windows and save them again.

Is there a file or place that I can save on my PC that remembers the settings that I want?

Sorry for any confusion. I'm not very adept with this kind of stuff.

**Comment by kangyu-california** [comment]
After PC reboot, PW restore menu become grey, you may exit PW, then relaunch PW manually.

If the issue is gone, chances are your auto start task in not configured property, either missing -delay_start argument suggested in readme, or missing trigger.
Please follow [discussion thread](https://github.com/kangyu-california/PersistentWindows/discussions/232) search for auto_start_task.zip
