### ISSUE TITLE
When leaving windows maximized, they save this size as windows size

### ISSUE THREAD

**Issue by Matt-17** [kangyu-california/PersistentWindows#259]
For some reason, when I maximized a window, the window will stay later this size when unmaximizing. 

As far as I know, you must not store the window size, when a window is maximized because it has the values of the screen size. 

Hope you know, what I mean.

**Comment by kangyu-california** [comment]
A window could have two sizes, one for maximized state and the other for normal state (aka unmaximized)
PW knows the difference, and would not overwrite normal size with maximized size.

"As far as I know, you must not store the window size, when a window is maximized because it has the values of the screen size."
This is not true, some software allows user to maximize a window relative within a predefined zone instead of filling up whole screen. That is why PW has to restore maximized window using size data.

I don't think the problem is due to PW misbehave.
