### ISSUE TITLE
Is there a way to temporarily turn off "PersistentWindows"? Or apply to just certain apps?

### ISSUE THREAD

**Issue by Archeol** [kangyu-california/PersistentWindows#26]
Sometimes I don't really want the windows restored to how I "captured windows to disk", as I would like a monitor to be off. Maybe I'm not using it right, but wasn't this supposed to leave everything simply based on where the applications were when turning off the monitors? Or is it purely based on how you "captured windows to disk"? Cause having the windows forcefully open up to one monitor seems to just create the same problems, but on the other side this time. Of course I'm probably in the minority here when I just use one monitor instead of both, but I'm hoping I'm just screwing something up here for more ease of life.

An issue that I think is related to this:
I find that having videos set at full screen (YouTube's the only one I've tried) then turning off the monitor makes things very wonky, to replicate:
- First, the YouTube video is set to full screen on the OTHER monitor than google chrome was "captured windows to disk" to
- Then, I turn off both monitors, one being the weird undetectable one cause of DisplayPort or something (this is the "OTHER monitor" mentioned above)
- Then, turn both back on and the fullscreen video will show up on the set "captured windows to disk" side
- Then, turn off fullscreen and it flips to the other side
- Then, minimize the window and it switches back over yet again but stays put thereafter

**Comment by kangyu-california** [comment]
Hi,

There are multiple issues raised here. Not quite sure I understand all of them, maybe a video clip may help.

I do have a plan to detect monitor power off event and let it trigger automatic restore, because Windows might not send display setting change message as expected. The enhancement will be available in August.

For temporary turn off automatic restore, this is an interesting feature that I have considered before. Since we have a real use case now, I will add a menu item "Stop/Resume automatic restore" in the next release (4.29) around 7/25

According to a prior issue report, manual restore from disk has a failure rate round 50%, I am still investigating the issue. The bet is to do manual restore multiple times.

Thanks for the feedback

**Comment by Archeol** [comment]
I've made some small edits to hopefully clarify what's going on, cause I'm new to github and don't really see the option for video.

A summary to hopefully clarify:
- the first paragraph is just an ease of life request.
- the second paragraph with the bullet points is one related example as to why I would want that ease of life request; it was an attempt to give steps as to how to recreate the weird **_switcharoos_** I'm encountering. Again, I can try to make a video but I wouldn't even know how to share it.

**Comment by kangyu-california** [comment]
Turn off/on function is implemented in Version 4.29 via "pause/resume auto restore" menu, please try.

**Comment by Archeol** [comment]
Yup, it's fantastic! works exactly like I wanted, thanks.
