### ISSUE TITLE
Taskbar moves to bottom position

### ISSUE THREAD

**Issue by MrD-RC** [kangyu-california/PersistentWindows#278]
I have my taskbar on the left side of my main monitor. Sometimes when the desktop is resumed. The taskbar reverts to a bottom position.

**Comment by kangyu-california** [comment]
Please latest 5.49 release

**Comment by MrD-RC** [comment]
> Please upgrade to latest 5.49 release

I am using version 5.49.8768.33245

When I switched on my PC this morning, the task bar was back at the bottom of the screen.

**Comment by kangyu-california** [comment]
To help reproduce the issue, please run following
[PersistentWindows5.49_278.zip](https://github.com/kangyu-california/PersistentWindows/files/13868884/PersistentWindows5.49_278.zip)

Once the issue is reproduced on your machine, please launch event viewer then go to Application section, click "Filter Current Log" from the Actions panel, specify 9990,9999 events in last 12 hours, click OK. Then click "Save Filtered Log File As", and upload the saved .evtx file.
![image](https://github.com/kangyu-california/PersistentWindows/assets/59128756/8e7a3caa-1dc6-4caf-90c4-05322a18f0a1)

**Comment by kangyu-california** [comment]
Never mind, I have reproduced the issue on my computer.
Will update when fix is ready.

**Comment by kangyu-california** [comment]
One more question, does this issue happen only when exit from full-screen game playing?

**Comment by MrD-RC** [comment]
On that PC I never play games. It happens on boot or when returning from screensaver/monitor standby.

**Comment by kangyu-california** [comment]
Please try https://github.com/kangyu-california/PersistentWindows/releases/tag/5.49_patch

**Comment by kangyu-california** [comment]
Formal release https://github.com/kangyu-california/PersistentWindows/releases/tag/5.50
