### ISSUE TITLE
Issue with the new "Webpage Commander" feature accidentally being triggered while gaming

### ISSUE THREAD

**Issue by mitchell-gilbertson** [kangyu-california/PersistentWindows#329]
Hi there,

I've been having an issue since this Webpage Commander feature was added where I accidentally trigger it while playing a game, and the overlay comes up over my game causing me to be unable to interact with my game in the area where the overlay appears. I've been dragging it off to my second monitor when this happens but it's unfortunately caused more than a few frustrated gamer moments.

I saw the other thread debating on whether this should be a feature included in this tool or not, but I'm not here to argue about that. I could see myself potentially finding a use for it even. I just wish there was either a toggle option to enable or disable the keyboard shortcut, or an option to customize the keyboard shortcut itself.

I realize I could probably just download the source code and modify it myself, and I'll probably give that a try, but I just make WordPress websites so I'd just be finding that keyboard shortcut variable, changing it and hope that doesn't break anything. I wouldn't know where to begin with adding an option to the interface for that.

I really appreciate this tool you've created though, it saves me so much frustration. Thanks.

**Comment by kangyu-california** [comment]
Please try latest patch
[PersistentWindows5.54_patch4.zip](https://github.com/user-attachments/files/15797061/PersistentWindows5.54_patch4.zip)

In case webpage commander still comes into the play in a unwanted way, you may disable the hotkey by running PW with command line option -webpage_commander_window=0
or -hotkey "Q"  if user want to change the hotkey to Alt + Q instead of Alt + W

**Comment by mitchell-gilbertson** [comment]
This worked perfectly. Thank you so much!
