### ISSUE TITLE
Windows taskbar getting placed at random edges when restoring windows

### ISSUE THREAD

**Issue by chiefthomson** [kangyu-california/PersistentWindows#344]
Hi,
I hope this is ok to raise, didn't know how else to get in contact.
My issue, I have 2 monitors via Windows Pro 10.0.19045:
1st : 4k monitor in landscape mode
2nd : 1k monitor in portrait mode

My Windows taskbar is always on the first monitor on the left edge. At the beginning when I started using this software, the taskbar was also locked. Persistant Windows, upon every restore, places the taskbar at different places. Mostly to be fair (70-80%) it's being placed on the first monitor bottom, but I've seen it several times suddenly being on the 2nd monitor left side, 2nd monitor bottom side and 1st monitor right side. I had to remove the locked taskbar setting in order to constantly move it back, so both settings locked/unlocked don't seem to have an impact.
I run the software in its default configuration, install and let it do its thing. Anything else perfectly works.
I use 5.57.8960.40781.

Let me know if I can help with investigation or deliver more content.
Thanks

**Comment by kangyu-california** [comment]
The issue is likely to be caused by inaccurate taskbar position report by Windows OS during PW auto restore.
One thing you can try is to let Windows OS settle down taskbar position first before PW auto restore start.
The command line option is like
-delay_auto_restore 2.5
where 2.5 is the second to wait when display config change is detected, increase that value as your config requires.

**Comment by chiefthomson** [comment]
Thanks a lot for the response.
I had to try a couple of delays, 6 seconds was the sweet spot to avoid the issue... I guess I've got slow monitors when waking up.
