### ISSUE TITLE
Disable Webpage Commander by default

### ISSUE THREAD

**Issue by Mermothle** [kangyu-california/PersistentWindows#347]
I know there's already posts about how to disable it via Task Scheduler, but this is a bit of a different issue.

This keybind is actually becoming an issue for some people. Accidentally hitting ALT+W or the other keybind causes this feature to activate. I have it set to disabled in Task Scheduler, but the issue is PersistentWindows is very prone to crashing, so if I turn it on quickly i.e. via the windows search bar, Webpage Commander is on by default. I thought I caught a virus when a little blue box started following my cursor around, I restarted my computer the first time it happened.

There's posts on google and reddit of people confused about this weird blue box (webpage commander) following their cursor around and having no idea what it is, there's even one I saw on the microsoft support forum. Who would guess that this blue box with strange behavior is tied to a program that's just supposed to keep your windows in place after turning your monitor off? If there's no option to permanently remove it without using task scheduler commands, then I ask that the program remembers the user's last chosen option at least. Turn it off by default, please, and if someone wants to use it, they can enable it and the program can remember that choice. It's caused me a lot of trouble and it's really, really annoying to have to either launch it exclusively through task scheduler or manually turn it off every time, but if anyone wanted the accessibility features, they should be able to turn it on and have their choice remembered.

**Comment by Dr-Sparx** [comment]
I completely agree with this suggestion. I have just spent far too much time working out why Alt-W stopped working in a program that I am running over X11. PersistentWindows was certainly not on my radar, and the program in question has nothing to do with any web browser (it's a [Linux file manager](http://silk.apana.org.au/fc.html)). I started looking at the _Issues_ because I couldn't quite work out how/where to specify `-webpage_commander_window=0`. It's been too long that that was configured.

**Comment by kangyu-california** [comment]
I think the real problem is inadequate GUI notification when the feature is activated, causing user to puzzle.

Please try [5.57_patch3](https://github.com/user-attachments/files/16620301/PersistentWindows5.57_patch3.zip)

The patch contains two fixes,
1. The default setting for webpage commander feature remains on by default. When the feature is invoked by Alt + W inside a web browser for the first time, a notification will popup from taskbar tray icon area, and the web browser will be redirected to a PW notification web page.
2. press Alt + W hotkey from task bar will no longer invoke webpage commander

@Mermothle "the issue is PersistentWindows is very prone to crashing", please get the call stack info of the crash from event viewer and submit bug.
@Dr-Sparx  I could not find the evidence that Alt + W hotkey is used by the linux file manager. pls elaborate when you have time

Thanks for the bug report.

**Comment by Mermothle** [comment]
This is very helpful with alerting people to what Webpage Commander is doing, which is a solid step. (The patch works as intended.) If I crash again (usually after shutting the monitor on and off, so it never applies the windows), I'll see about getting the log, but I don't really mind that it does - it was just frustrating that quick-launching it afterwards always meant Webpage Commander would be turned on by default. It requires people to run it through Task Scheduler or create a shortcut specifically for this app, but the issue there is the help page doesn't say that disabling it in the right click menu is temporary; the other two methods are permanent, but disabling it via the right click menu is not. PersistentWindows requires a level of micromanagement that isn't really big, but one that other apps don't have when shutting off unwanted features. I think making the right click menu remember the user's choice of disabling it is really the last thing this needs to make it more convenient for the user, since it seems to be able to remember the first time it's launched now, and it remembering the choice too would be perfect. This is a really good QOL update, though, so I'm grateful for that.

**Comment by Dr-Sparx** [comment]
>@Dr-Sparx I could not find the evidence that Alt + W hotkey is used by the linux file manager. pls elaborate when you have time

Alt ... starts a file name search, from the FCL help: 
`Alt-[printable char] - Search for file name in current dir starting with characters typed.`

With Alt + W being captured elsewhere, I could no longer jump to directories or files starting with W.
