### ISSUE TITLE
 disable during fullscreen

### ISSUE THREAD

**Issue by rkotenko** [kangyu-california/PersistentWindows#35]
I really like the work you have done here.  It saves me a great deal of annoyance when switching monitor sources for work.

On thing though.  If I am playing a game in fullscreen and need to get back to another app for a second, I can't.  When I try to Ctrl-Tab to a different program, this software kicks in and immediately reverts back to the fullscreen.  Right now, it means I have to turn PersistentWindows off when playing a game and the remember to turn it back on after I am done.

Could you add some sort of detection to not save fullscreens and try to restore them?  Even just some sort of option to enable it would be great. 

Thanks!

**Comment by kangyu-california** [comment]
This issue sounds like a replicate of issue #20 which was resolved since version 4.10
Please make sure to run the latest version.

To switch out of full screen game mode, press Alt-Tab or Ctrl-Esc key

If the issue still exist, please follow the guide in the "Tips for power user" section (copy & paste content of event 9990 and 9999 from Event Viewer). I need to examine the event sequence before commit the requested change.

Thx!

**Comment by rkotenko** [comment]
Yeah, that was my bad.  I was way behind on versions.  Should have searched the issues.
