### ISSUE TITLE
Windows restoring not works with TV with DSR

### ISSUE THREAD

**Issue by bjakja** [kangyu-california/PersistentWindows#37]
I install your program to avoid shrinking windows when turn off display sometimes and when change it to 640 x 480 every window. After turn off monitor and have TV on standby and turn on TV windows are shrink and after turn on to primary monitor restored was only not minimized window. For me program solves nothing, maybe it's because Dell monitors causes many several problems on display port. 
Monitor : Dell PH2419H
uses Display Port
TV: Phillips 32PFL8605H
uses HDMI

**Comment by bjakja** [comment]
Minimized windows was still minimized but after restore window have resolution 640 x 480.
I just downloaded latest version a week ago when I posted this issue.
Video I can record in Sunday.

**Comment by Syphilisto** [comment]
I have personally noticed a minimized window that I have recently moved will occasionally get restored to a prior location instead of staying where I moved it.  Waiting a second or so is a simple-enough workaround.  (What exactly is the poll rate for PW?)  I'm also not 100% sure what he meant, but i hope this tip was relevant.

**Comment by kangyu-california** [comment]
@Syphilisto Typical capture latency is 3 seconds to filter out OS initiated moves. If user made a second move during that period, the capture will be delayed 3 seconds further.

**Comment by bjakja** [comment]
After record a video, a see that after minimize it change resolution with weird jump, but works about 2 seconds after restore (when I change resolution in that time it not work). But on tv windows are still shrank, cause of DSR 4x (4k resolution on tv fullHD). On normal resolution it works even without your program. Looks like Your program not working with DSR that I use for one game that not shows resolution higher than set on monitor / TV.

**Comment by kangyu-california** [comment]
Although the key diagnostic information is still missing (application log in event viewer, picture or video to illustrate the issue), I am pretty sure that PersistentWindows will not be able to fix this issue, as the program is only reacting to display resolution change rather than causing or reverting the resolution change.

I would think the issue is with video card and/or TV hardware/driver/firmware.
Sorry I can not help with this issue any further.
