### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by eaglerock86** [kangyu-california/PersistentWindows#50]
Hi, first i wanted to thank you for making this amazing app.
I have been using it for over a month with no issues, but suddenly after installing and removing DisplayFusion, PersistentWindows stopped working :(
Any idea on what could be the reason ?

**Comment by kangyu-california** [comment]
Install/Uninstall displayfusion does not seem to affect PW on my test machine,
Here is a few more questions for you,
is PW process still alive? If it crashes, there should be a crash log in Event Viewer.
is PW GUI menu still working?
what is the latest Application event id 9990 and 9999 in Event Viewer?

Lastly I assume your PW version is old, please update to latest 4.40 version, and I would suggest running it with Admin privilege so that no other process can kill it.

**Comment by kangyu-california** [comment]
Please try latest release 4.41

If the issue still exist, you may reopen it.

**Comment by kangyu-california** [comment]
v4.41 is a lemon. pls try v 4.42

**Comment by eaglerock86** [comment]
Hi, thank you so much for the help, after deleting some registries and uninstalling the monitor drivers it seems to work again :)
