### ISSUE TITLE
PersistentWindows dont remember my capture after reboot pt2

### ISSUE THREAD

**Issue by dhaern** [kangyu-california/PersistentWindows#51]
Continue from issue #48 - Thanks for the update man but tested 4.41 and bug still not fixed, restore option greyed out after restart and I captured it before restart, db files not updating after I hit capture. Program is not reading/saving it good. Maybe I need install another Windows 10 version but I dont have problems with other software.

![image](https://user-images.githubusercontent.com/7317522/94860341-d647c800-042d-11eb-947f-526346b3285b.png)

**Comment by kangyu-california** [comment]
4.41 is a bad release, sorry for that.
I am not sure why capture to disk could fail, the coding style of accessing LiteDB package is exactly as documented.
Please try release 4.42, I have upgraded LiteDB package from 5.0.7 to latest 5.0.9, hope that helps.

Another place to look at is .Net framework version, some 4.x version is said to be causing loss of data due to bad caching.

**Comment by dhaern** [comment]
I tried everything, updated windows updates and Net Framework to latest version 4.8 (I had 4.7.2), cleaned registry and files with ccleaner technician edition latest version and tested new 4.42 version but bug still there, looks like the program cant read/write in that folder and overwrite db files, checked my ownership from the folder and added more permissions with this miniguide:

[https://appuals.com/how-to-fix-folder-keeps-reverting-to-read-only-on-windows-10/](https://appuals.com/how-to-fix-folder-keeps-reverting-to-read-only-on-windows-10/)

and still dont work, same bug.

Maybe you could add an user choice to let us install the folder locations with databases instead use the default "Appdata" folder? Also I noticed if I delete the folder and try run the program i get this error:

![image](https://user-images.githubusercontent.com/7317522/94883172-dbbf0580-0461-11eb-8e07-f983d1c6a150.png)

but program is not running! thanks.

**Comment by kangyu-california** [comment]
In 4.42 there is a new command line option -redirect_appdata
which allows you to read/write .db file on current dir instead of local/appdata/PersistentWindows

Note that current dir is literally "." which does not have to be the same as unzipped PW dir, with that new feature you may launch PW from any dir which you have R/W permission inside command console

Good luck!

**Comment by kangyu-california** [comment]
The false alarm of "Only one instance can be run" is fixed in release 4.43
Thanks a lot for your help on testing out all scenarios.

**Comment by dhaern** [comment]
> The false alarm of "Only one instance can be run" is fixed in release 4.43
> Thanks a lot for your help on testing out all scenarios.

Np man, I tried 4.43 and new -redirect_appdata command and no luck :(

I have my dbs in program folder located in desktop, I dont understand why but program only write one time when it creates the files and dont overwrite it after or read when restart.

**Comment by kangyu-california** [comment]
Try release 4.44 which optimized implementation of capture to disk by using incremental update instead of delete all followed by write all.
This implementation is more cache friendly.

Also it is now safe to repeat capture multiple times without worry about loss of data.

**Comment by dhaern** [comment]
Oh man, it's fixed!! I will test more days but finally it's working. Tested and rewrite when recapture is working, also after restart,  program is reading db files and I can restore every window and auto reposition it in 1 click. Thanks man!
