### ISSUE TITLE
V3.2 just came back from sleep with windows on wrong screens :-(

### ISSUE THREAD

**Issue by DavidG-Aus** [kangyu-california/PersistentWindows#7]

**Comment by kangyu-california** [comment]
Please try V3.4
Also note that PersistentWindows takes 3 seconds to capture user move, please allow sufficient time to capture window position before sleep.

**Comment by kangyu-california** [comment]
Please try V3.5

It turns out there is a small chance that window location is not fully restored, this is due to Windows OS sometimes fail to report actual location precisely.

If that happens again, immediately let the computer sleep, and then wake it up again. Most likely the window layout will be perfectly restored. Please do NOT make any operation such as move/minimize/maximize/reactivate window before sleep, otherwise the persistent window data would be contaminated and unable to do full recovery.

**Comment by kangyu-california** [comment]
V3.6 takes care of most occasional restore failures.

**Comment by kangyu-california** [comment]
V3.7 make further improvement to avoid miscaptures
