### ISSUE TITLE
Minimized window resets to other monitor after restoring it

### ISSUE THREAD

**Issue by GoaLitiuM** [kangyu-california/PersistentWindows#78]
When I move a window to another monitor and minimize it, then unminimize the same window again, the window resets back to the original position in other monitor.

Maybe the old window position should only be restored automatically within few seconds after monitor count changes, but this minimize/restore trick seems change the position when monitors have not changed recently?

May seem like a duplicate off #57 but this occurs while actively using the system, not after turning monitors on/off.

**Comment by kangyu-california** [comment]
The current version (5.12) requires user to wait for at least 1 second after moving window, otherwise the new location is not captured yet (when immediately minimize the window at new location) so the window will be restored to old location.

The "1 second latency" rule should be good enough for most users.
In latest commit, the  1 second latency is further reduced to almost 0.
 
As the fix is not so urgent,  my plan is to release it in next week. 
You may need to build a executable for testing on your own.
