### ISSUE TITLE
Task Bar Persists

### ISSUE THREAD

**Issue by sekh0n** [kangyu-california/PersistentWindows#91]
A current issue I am having is that the task bar stays above any full screen application.

Even if full screen a youtube video, for example, the task bar is visible above the scrubbing area and I have to hit 'esc' to be able to exit.

**Comment by kangyu-california** [comment]
By default taskbar would stay above other windows, I believe this is not caused by PW.

However PW can help to clear the topmost flag of any window. The solution is documented in the last section of online help.
In short, click the taskbar first, then hold CTRL key pressed and click the youtube window

**Comment by sekh0n** [comment]
I haven't experienced this before downloading PW.

I closed PW and took it out of the startup process and the issue went away after a restart.

Thanks for the solution, from where I stand seems to be an interaction with PW, but I don't have that much knowledge on the situation as you can probably tell.

I appreciate your work on PW. Thank you!

**Comment by kangyu-california** [comment]
I used to have this sticky taskbar issue in prior Windows10 releases, 
now I don't see this issue anymore.

So you might want to upgrade your windows 10 version to latest (20H2)
